// "In one sentence, describe the NPC's occupation and provide a brief
// historical note that hints at the character's past"
export const occupationAndHistory = [];

export const appearance = [
  "Distinctive jewelry: earrings, necklace, circlet, bracelets",
  "Piercings",
  "Flamboyant or outlandish clothes",
  "Formal, clean clothes",
  "Ragged, dirty clothes",
  "Pronounced scar",
  "Missing teeth",
  "Missing fingers",
  "Unusual eye color",
  "Different colored eyes",
  "Tattoos",
  "Face tattoos",
  "Covered in tattoos",
  "Birthmark",
  "Pale skin",
  "Dark skin",
  "Green-tinted skin",
  "Blue-tinted skin",
  "Bald",
  "Balding",
  "Short-cropped hair",
  "Long, flowing hair",
  "Scraggly beard",
  "Perfectly groomed beard",
  "Braided beard",
  "Red hair",
  "White hair",
  "Green hair",
  "Blue hair",
  "Pink hair",
  "Yellow hair",
  "Distinctive nose",
  "Unusually straight posture",
  "Crooked posture",
];

export const highAbility = [
  "brawny",
  "lithe",
  "agile",
  "graceful",
  "hardy",
  "healthy",
  "studious",
  "learned",
  "inquisitive",
  "perceptive",
  "spiritual",
  "insightful",
  "persuasive",
  "charismatic",
  "friendly",
  "forceful",
  "quick-witted",
];

export const lowAbility = [
  "clumsy",
  "fumbling",
  "dim-witted",
  "slow",
  "oblivious",
  "absentminded",
  "dull",
  "boring",
  "unfriendly",
  "dour",
  "taciturn",
  "belligerent",
  "crude",
  "vulgar",
  "awkward",
  "uncouth",
  "sinister",
  "menacing",
  "sneaky",
];

export const talents = [
  "Plays a musical instrument",
  "Speaks several languages fluently",
  "Unbelievably lucky",
  "Perfect memory",
  "Great with animals",
  "Great with children",
  "Great at solving puzzles",
  "Great at one game",
  "Great at impersonations",
  "Draws beautifully",
  "Paints beautifully",
  "Sings beautifully",
  "Drinks everyone under the table",
  "Expert carpenter",
  "Expert cook",
  "Expert dart thrower and rock skipper",
  "Expert juggler",
  "Skilled actor and master of disguise",
  "Skilled dancer",
  "Knows thieves' cant",
];

export const mannerisms = [
  "Prone to singing, whistling, or humming quietly",
  "Speaks in rhyme",
  "Speaks lyrically",
  "Particularly low voice",
  "Particularly high voice",
  "Slurs words",
  "Lisps",
  "Stutters",
  "Enunciates overly clearly",
  "Speaks loudly",
  "Whispers",
  "Uses flowery speech or long words",
  "Frequently uses the wrong word",
  "Uses colorful oaths and exclamations",
  "Makes export constant jokes or puns",
  "Prone to predictions of doom",
  "Twitches nervously",
  "Fidgets",
  "Squints",
  "Stares into the distance",
  "Chews something",
  "Paces",
  "Taps fingers",
  "Bites fingernails",
  "Twirls hair or tugs beard",
];

export const interactions = [
  "Argumentative",
  "Arrogant",
  "Blustering",
  "Rude",
  "Curious",
  "Friendly",
  "Honest",
  "Hot tempered",
  "Irritable",
  "Ponderous",
  "Quiet",
  "Suspicious",
];

export const goodIdeals = [
  "Beauty",
  "Charity",
  "Greater good",
  "Life",
  "Respect",
  "Self-sacrifice",
];

export const evilIdeals = [
  "Domination",
  "Greed",
  "Might",
  "Pain",
  "Retribution",
  "Slaughter",
];

export const lawfulIdeals = [
  "Community",
  "Fairness",
  "Honor",
  "Logic",
  "Responsibility",
  "Tradition",
];

export const chaoticIdeals = [
  "Change",
  "Creativity",
  "Freedom",
  "Independence",
  "No limits",
  "Whimsy",
];

export const neutralIdeals = [
  "Balance",
  "Knowledge",
  "Live and let live",
  "Moderation",
  "Neutrality",
  "People",
];

export const otherIdeals = [
  "Aspiration",
  "Discovery",
  "Glory",
  "Nation",
  "Redemption",
  "Self-knowledge",
];

export const bonds = [
  "Dedicated to fulfilling a personal life goal",
  "Protective of close family members",
  "Protective of colleagues or compatriots",
  "Loyal to a benefactor, patron, or employer",
  "Captivated by a romantic interest",
  "Drawn to a special place",
  "Protective of a sentimental keepsake",
  "Protective of a valuable possession",
  "Out for revenge",
  // 'Roll twice, ignoring results of 10',
];

export const flawsSecrets = [
  "Forbidden love or susceptibility to romance",
  "Enjoys decadent pleasures",
  "Arrogance",
  "Envies another creature's possessions or station",
  "Overpowering greed",
  "Prone to rage",
  "Has a powerful enemy",
  "Specific phobia",
  "Shameful or scandelous history",
  "Secret crime or misdeed",
  "Possession of forbidden lore",
  "Foolhardy bravery",
];
