exports.fantasy = [
  'Abrielle',
  'Acalia',
  'Adair',
  'Adara',
  'Adon',
  'Adriel',
  'Agro',
  'Aiyana',
  'Alaire',
  'Alissa',
  'Alixandra',
  'Altair',
  'Amara',
  'Anatola',
  'Anya',
  'Arcadia',
  'Ariadne',
  'Arianwen',
  'Arlo',
  'Aurelia',
  'Aurelian',
  'Aurelius',
  'Auristela',
  'Avalon',
  'Azamarr',
  'Baashar',
  'Barak',
  'Barton',
  'Baske',
  'Bastian',
  'Baxar',
  'Blaiz',
  'Breena',
  'Briallan',
  'Brielle',
  'Briseis',
  'Caelan',
  'Cambria',
  'Cara',
  'Carys',
  'Caspian',
  'Cassia',
  'Cassian',
  'Cassiel',
  'Cassiopeia',
  'Cassius',
  'Chaniel',
  'Clawsen',
  'Colborn',
  'Cora',
  'Corbin',
  'Cyprian',
  'Dagen',
  'Dagfinn',
  'Dagrod',
  'Daire',
  'Darius',
  'Destin',
  'Devlin',
  'Devlyn',
  'Dimian',
  'Domnhar',
  'Drake',
  'Drystan',
  'Ebraheim',
  'Eira',
  'Eirian',
  'Eldermar',
  'Eliron',
  'Elysia',
  'Embre',
  'Eoin',
  'Esdel',
  'Eune',
  'Evadne',
  'Evanth',
  'Fangar',
  'Favroe',
  'Feron',
  'Feston',
  'Fineas',
  'Finian',
  'Fintis',
  'Fyodor',
  'Gaerwn',
  'Gareth',
  'Gatlen',
  'Gatlin',
  'Gavriel',
  'Gentar',
  'Gethrod',
  'Ginerva',
  'Graff',
  'Griffin',
  'Guinevere',
  'Gunnar',
  'Hadriel',
  'Hagalbar',
  'Hannelore',
  'Hawke',
  'Hemm',
  'Henndar',
  'Hermione',
  'Hesperos',
  'Hezra',
  'Hodus',
  'Iagan',
  'Ianthe',
  'Ignacia',
  'Ignatius',
  'Iseult',
  'Ishmael',
  'Isolde',
  'Jakrin',
  'Jareth',
  'Jaris',
  'Jather',
  'Jerrick',
  'Jessalyn',
  'Jessop',
  'Jinto',
  'Joz',
  'Kadric',
  'Kagran',
  'Kara',
  'Katriel',
  'Kent',
  'Kerensa',
  'Khron',
  'Kontas',
  'Korbin',
  'Krinn',
  'Kyler',
  'Kyra',
  'Kyrielle',
  'Lassrin',
  'Leala',
  'Leila',
  'Leira',
  'Lenox',
  'Lilith',
  'Liora',
  'Liriene',
  'Liron',
  'Lothe',
  'Lucien',
  'Lustros',
  'Lydan',
  'Lyra',
  'Maia',
  'Marius',
  'Mathieu',
  'Mavrek',
  'Maylea',
  'Meira',
  'Mireille',
  'Mireya',
  'Moki',
  'Natania',
  'Nazim',
  'Neirin',
  'Nerys',
  'Nesso',
  'Nuriel',
  'Nyfain',
  'Nyssa',
  'Oisin',
  'Oleisa',
  'Ophni',
  'Oralie',
  'Orinthea',
  'Orion',
  'Orpheus',
  'Ozara',
  'Pakker',
  'Paquin',
  'Paskel',
  'Peregrine',
  'Persephone',
  'Perseus',
  'Petronela',
  'Phelan',
  'Pike',
  'Pryderi',
  'Ptorik',
  'Pyralia',
  'Pyralis',
  'Qadira',
  'Quinevere',
  'Quintessa',
  'Quintis',
  'Raisa',
  'Rankar',
  'Remus',
  'Renfrew',
  'Renham',
  'Revvyn',
  'Rhyan',
  'Rhydderch',
  'Riona',
  'Riordan',
  'Rivik',
  'Rourke',
  'Roux',
  'Ryven',
  'Saira',
  'Saoirse',
  'Sarai',
  'Sarielle',
  'Sarkin',
  'Sebastian',
  'Seraphim',
  'Seraphina',
  'Serian',
  'Séverin',
  'Sirius',
  'Sorcha',
  'Straus',
  'Syrin',
  'Talon',
  'Tavish',
  'Tearlach',
  'Tekren',
  'Terra',
  'Tez',
  'Thalia',
  'Thaniel',
  'Theia',
  'Torian',
  'Torin',
  'Tressa',
  'Tristana',
  'Turrek',
  'Tyvrik',
  'Ulyssia',
  'Uriela',
  'Urien',
  'Vadim',
  'Vale',
  'Vanora',
  'Varog',
  'Vasilis',
  'Verssek',
  'Vespera',
  'Weston',
  'Whit',
  'Wulfe',
  'Xanthus',
  'Xara',
  'Xylia',
  'Yadira',
  'Yakira',
  'Yeira',
  'Yeriel',
  'Yestin',
  'Yorjan',
  'Yseult',
  'Zaden',
  'Zagaroth',
  'Zaira',
  'Zaniel',
  'Zarek',
  'Zenner',
  'Zephyr',
  'Zora',
  'Zorion',
];

exports.romanian = [
  'Adam',
  'Adela',
  'Adelina',
  'Adi',
  'Adina',
  'Adrian',
  'Adriana',
  'Albert',
  'Alex',
  'Alexandra',
  'Alexandru',
  'Alin',
  'Alina',
  'Amalia',
  'Ana',
  'Anamaria',
  'Anastasie',
  'Anca',
  'Ancuța',
  'Andra',
  'Andrada',
  'Andreea',
  'Andrei',
  'Angela',
  'Angelica',
  'Anghel',
  'Ani',
  'Anișoara',
  'Anton',
  'Antonia',
  'Antoniu',
  'Apostol',
  'Atanase',
  'Atanasie',
  'Augustin',
  'Aurel',
  'Aurelia',
  'Aurica',
  'Aurică',
  'Aurora',
  'Beniamin',
  'Bianca',
  'Bogdan',
  'Bogdana',
  'Brândușa',
  'Camelia',
  'Carmen',
  'Carol',
  'Casandra',
  'Cătălin',
  'Cătălina',
  'Catina',
  'Catrinel',
  'Cecilia',
  'Cezar',
  'Cezara',
  'Ciprian',
  'Clara',
  'Claudia',
  'Claudiu',
  'Codrin',
  'Codruț',
  'Constanța',
  'Constantin',
  'Corina',
  'Cornel',
  'Cornelia',
  'Corneliu',
  'Cosmin',
  'Cosmina',
  'Costache',
  'Costel',
  'Costică',
  'Costin',
  'Crina',
  'Cristi',
  'Cristian',
  'Cristina',
  'Dacian',
  'Daciana',
  'Dan',
  'Dana',
  'Daniel',
  'Daniela',
  'Dănuț',
  'Daria',
  'Darius',
  'David',
  'Decebal',
  'Delia',
  'Demetra',
  'Denis',
  'Denisa',
  'Diana',
  'Dinu',
  'Dionisie',
  'Doina',
  'Dorin',
  'Dorina',
  'Dorinel',
  'Doru',
  'Dragomir',
  'Dragos',
  'Dragoș',
  'Dumitra',
  'Dumitru',
  'Ecaterina',
  'Eduard',
  'Elena',
  'Elisabeta',
  'Emanoil',
  'Emanuel',
  'Emanuela',
  'Emil',
  'Emilia',
  'Emilian',
  'Eugen',
  'Eugenia',
  'Eusebiu',
  'Fane',
  'Felicia',
  'Felix',
  'Filip',
  'Flavia',
  'Flaviu',
  'Florentin',
  'Florin',
  'Florina',
  'Gabi',
  'Gabriel',
  'Gabriela',
  'Gavril',
  'Gavrila',
  'George',
  'Georgeta',
  'Georgiana',
  'Ghenadie',
  'Gheorghe',
  'Ghiță',
  'Grigore',
  'Haralamb',
  'Horațiu',
  'Horea',
  'Horia',
  'Iacob',
  'Iancu',
  'Ignat',
  'Ileana',
  'Ilie',
  'Ilinca',
  'Ioan',
  'Ioana',
  'Iolanda',
  'Ion',
  'Ionel',
  'Ionela',
  'Ionuț',
  'Iosif',
  'Irina',
  'Isabela',
  'Isabella',
  'Isac',
  'Iulia',
  'Iulian',
  'Iuliana',
  'Iuliu',
  'Ivan',
  'Larisa',
  'Laura',
  'Laurențiu',
  'Lavinia',
  'Lenuța',
  'Leonard',
  'Liana',
  'Lidia',
  'Ligia',
  'Liliana',
  'Livia',
  'Liviu',
  'Loredana',
  'Lorena',
  'Luca',
  'Lucia',
  'Lucian',
  'Luiza',
  'Luminița',
  'Mădălina',
  'Magda',
  'Magdalena',
  'Manuel',
  'Manuela',
  'Marcel',
  'Marcela',
  'Margareta',
  'Maria',
  'Marian',
  'Mariana',
  'Maricica',
  'Marilena',
  'Marin',
  'Marina',
  'Marius',
  'Marta',
  'Martin',
  'Matei',
  'Mihaela',
  'Mihai',
  'Mihail',
  'Mihăiță',
  'Minodora',
  'Mircea',
  'Mirela',
  'Miron',
  'Miruna',
  'Mitică',
  'Monica',
  'Narcisa',
  'Natalia',
  'Neculai',
  'Nelu',
  'Nicolae',
  'Nicoleta',
  'Nicu',
  'Nicușor',
  'Oana',
  'Octavian',
  'Olga',
  'Olimpia',
  'Otilia',
  'Ovidia',
  'Ovidiu',
  'Ozana',
  'Paul',
  'Paula',
  'Petre',
  'Petrică',
  'Petronela',
  'Petru',
  'Petruț',
  'Pompiliu',
  'Radu',
  'Rahela',
  'Raluca',
  'Ramona',
  'Rareș',
  'Răzvan',
  'Remus',
  'Robert',
  'Rodica',
  'Roxana',
  'Rozalia',
  'Ruxandra',
  'Sabina',
  'Sanda',
  'Sandra',
  'Sandu',
  'Sebastian',
  'Serafim',
  'Serghei',
  'Sergiu',
  'Silvia',
  'Silviu',
  'Simion',
  'Simon',
  'Simona',
  'Sofia',
  'Sonia',
  'Sorin',
  'Sorina',
  'Stan',
  'Ștefan',
  'Ștefania',
  'Stela',
  'Stelian',
  'Steliana',
  'Tatiana',
  'Teodor',
  'Teodora',
  'Tereza',
  'Theodor',
  'Tiberiu',
  'Timotei',
  'Toma',
  'Traian',
  'Tudor',
  'Valentin',
  'Valentina',
  'Valeria',
  'Valerian',
  'Valeriu',
  'Vali',
  'Vasile',
  'Vasilica',
  'Vasilică',
  'Veaceslav',
  'Vera',
  'Veronica',
  'Victor',
  'Victoria',
  'Violeta',
  'Viorel',
  'Viorica',
  'Virgil',
  'Virgiliu',
  'Virginia',
  'Vlad',
];

exports.towns = [
  'Noble Crest Stables',
  'Gibb’s Farm',
  'Triple Axes Pub',
  'Arrowhead Inn',
  'Yeomen’s Manor',
  'Bootstraps & Buckles Cobbler',
  'Dwarf’s Gullet Tavern',
  'Hollowvale Village',
  'Thunder Hoof Stables',
  'Clipper’s County',
  'Gresgo’s Pond',
  'Hemm’s Tailors',
  'Ditch’n’Dagger Tavern',
  'Twin Horses Lake Town',
  'Boggs Landing',
  'Heatherstown Village',
  'Trekker’s Square',
  'Embris Hollow',
  'Zagoroth Mountain Town',
  'Padsley Village',
  'Sleeping Dragon Inn',
  'Ramoth Lye Creek',
  'Dragmire Drove',
  'Archer’s Ale House',
  'Peeker’s Valley',
  'Anvil & Flint Blacksmithery',
  'Artwork by Jongmin Ahn',
  'Pale Thorn Cove',
  'Fang Peak',
  'Arc of the Holy Shield Monastery',
  'Breggo’s Beard Brewery',
  'Golden Stalk Granary',
  'Saw and Splinter’s Woodshop',
  'Siren’s Shipyard',
  'Silver Fin Fishery',
  'Addler’s Drove',
  'Black Morrow Marshes',
  'Shepherd’s Field',
  'Honeyclover Meadow',
  'Finch & Fox Inn',
  'The Warren Pub',
  'Fennel & Fallow Bakery',
  'Rose & Crown Tavern',
  'Knight’s Motte and Bailey',
  'White Elk Hall',
  'Briar Bridge Village',
  'Mighty Hart Furriers',
  'Ekhart Bridge',
  'The Magpie’s Market',
  'Thresh’s Cove',
  'Denmarrow Mountains',
  'Simple Beasts Watering Hole',
  'Lowly Strider Almshouse',
  'Miss Plunkerhouse’s Grand Tailors',
  'White Lion Halls',
  'Thousand Lanterns Inn',
  'Wild Hare Country Tavern',
  'Laskerville Village',
  'Scout’s Towers',
  'Golden Longbow Fields',
  'Tuckborrow Village',
  'Trader’s Turn Plaza',
  ' Stoneburrow Town',
  'Brather’s Town',
  'Stout Dragon Tavern',
  'Dueling Swords Blacksmithery',
  'The Braided Plait Bakery',
  'Mossy Stone Cove',
  'Fairy Winds Beach',
  'Old Stone Giant Mill',
  'Sacred Scroll Holy Monastery',
  'King Rothenham Square',
  'Brewer’s Bounty Alehouse',
  'Oslocrest Town',
  'Parsca’s Plaza',
  'Old Mayfield Farms',
  'Fowler’s Prize Furrers',
  'Iron Halberd Smithy',
  'Dukes Valley',
  'Burrowing Badger Inn',
  'Pork Belly’s Butcher Shop',
  'Cast Iron Almshouse',
  'Three Braided Beards Tavern',
  'King’s Own Tailors',
  'County Arms Smithy',
  'Golden Rise Bakery',
  'Spotted Finch Meadows',
  'Fairy Sisters Pasture',
  'Twin Owls Inn',
  'Snow Bard Village',
  'DarkVale Valley',
  'Tallard’s Orchards',
  'Two Moons Cove',
  'Star Fin Shipyard',
  'White Wind Mill Bakery',
  'Troll’s Hand Masons',
  'Vatrecastle Village',
  'Archer’s Arm Tavern',
  'Throne of the Ancient One Temple',
  'Swift Axes Woodcutter Shoppe ',
  'Evenly Yoked Stables',
  'Open Hands Almshouse',
  'Far Wren Village',
];
